language: node_js
node_js:
  - "6"

before_deploy:
  - hexo generate # generate static site
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master
  repo: niniliwei/niniliwei.github.io
  local_dir: public
  target_branch: master
  fqdn: https://blog.niniliwei.com
  project_name: blog.niniliwei.com
